import { LABELS, type Repo } from "../config.js";
import * as gh from "../github.js";
import type { DynamicWorkflowRun } from "../github.js";
import * as log from "../log.js";
import { reportError } from "../error-reporter.js";
import { ensureAlertIssue, closeAlertIssueIfResolved } from "../occurrence-tracking.js";
import { renderViolationTable } from "./scanner-runner.js";
import { mapSettledWithConcurrency } from "../util.js";
import { isGitHubHostedLabel } from "./workflow-parser.js";

const NAME = "dynamic-workflow-runner-scanner";
const ISSUE_TITLE = "Alert: dynamic workflows are running on GitHub-hosted runners";
const REPO_CONCURRENCY = 4;
const GITHUB_HOSTED_RUNNER_GROUP = "GitHub Actions";

/** A path whose latest run is older than this is dead, not "running on GitHub-hosted runners" —
 *  every managed repo's dependabot schedule is weekly, so 14 days is 2x the slowest live cadence. */
const MAX_RUN_AGE_MS = 14 * 24 * 60 * 60 * 1000;

/** GitHub's legacy Pages build always executes on GitHub's own infrastructure and — unlike
 *  Dependabot's updater — has no runner-label setting to point at a self-hosted runner, so an
 *  alert on it is permanently unactionable (#2339). */
const UNACTIONABLE_PATH_RE = /^dynamic\/pages\//;

export { ISSUE_TITLE };

const REMEDIATION = [
  "### How to fix this",
  "",
  "Dynamic workflows (Dependabot's updater, CodeQL default setup, etc.) are generated by " +
    "GitHub from a repository/org setting rather than a file in the tree — there is no " +
    "`.github/workflows/*.yml` entry to point `runs-on:` at, so this can only be fixed at the " +
    "setting that generates the workflow, not in this repo's files.",
  "",
  "For Dependabot's updater specifically, the runner is controlled **org-wide, not per repo**: " +
    "**Org Settings → Security → Advanced Security → Global settings → Dependabot → Runner " +
    "type → Labeled runner → Runner label**. Both self-hosted runners already answer " +
    "`self-hosted,linux`, so pointing that field at `linux` moves every repo's Dependabot " +
    "updater onto self-hosted runners with no per-repo change needed.",
].join("\n");

export interface Violation {
  path: string;
  runId: number;
  htmlUrl: string;
  jobName: string;
  labels: string[];
  runnerGroupName: string | null;
}

/** True when a job's runner identity is a billed GitHub-hosted runner rather than self-hosted. */
export function isGitHubHostedJob(job: { labels: string[]; runnerGroupName: string | null }): boolean {
  if (job.runnerGroupName === GITHUB_HOSTED_RUNNER_GROUP) return true;
  return job.labels.some((l) => isGitHubHostedLabel(l));
}

/** Latest run per distinct dynamic-workflow path — only current state matters: a path that has
 *  since moved to self-hosted must not keep alerting on an old hosted run. */
export function latestRunByPath(runs: DynamicWorkflowRun[]): DynamicWorkflowRun[] {
  const latest = new Map<string, DynamicWorkflowRun>();
  for (const run of runs) {
    const current = latest.get(run.path);
    if (!current || Date.parse(run.createdAt) > Date.parse(current.createdAt)) {
      latest.set(run.path, run);
    }
  }
  return [...latest.values()];
}

/** The dynamic-workflow runs worth checking: drops paths GitHub gives us no way to move off its
 *  own runners, keeps the latest run per remaining path, then drops paths whose latest run is
 *  stale — a dead path must age out so its alert can auto-close (#2339). */
export function selectScannableRuns(
  runs: DynamicWorkflowRun[],
  now: number = Date.now(),
): DynamicWorkflowRun[] {
  const actionable = runs.filter((r) => !UNACTIONABLE_PATH_RE.test(r.path));
  return latestRunByPath(actionable).filter(
    (r) => now - Date.parse(r.createdAt) <= MAX_RUN_AGE_MS,
  );
}

export function buildBody(repo: string, violations: Violation[]): string {
  return renderViolationTable({
    intro:
      `\`${repo}\`: dynamic workflow job(s) are executing on billed GitHub-hosted runners.\n`,
    columns: ["Workflow", "Job", "Runner", "Latest run"],
    rows: violations,
    cells: (v) => [
      `\`${v.path}\``,
      v.jobName,
      v.runnerGroupName ?? v.labels.join(", "),
      `[${v.runId}](${v.htmlUrl})`,
    ],
    footer: [REMEDIATION],
  });
}

async function scanRepo(repo: Repo): Promise<void> {
  const runs = await gh.listDynamicWorkflowRuns(repo.fullName);
  if (runs.length === 0) return;

  const violations: Violation[] = [];
  for (const run of selectScannableRuns(runs)) {
    // getRunJobRunnerInfo throws on anything but a deleted run (404), so an inconclusive
    // fetch propagates out of scanRepo to run()'s catch instead of silently reading as
    // "no violations" and closing a live alert below.
    const jobs = await gh.getRunJobRunnerInfo(repo.fullName, run.runId);
    for (const job of jobs) {
      if (isGitHubHostedJob(job)) {
        violations.push({
          path: run.path,
          runId: run.runId,
          htmlUrl: run.htmlUrl,
          jobName: job.name,
          labels: job.labels,
          runnerGroupName: job.runnerGroupName,
        });
      }
    }
  }

  if (violations.length === 0) {
    await closeAlertIssueIfResolved({
      repo: repo.fullName,
      title: ISSUE_TITLE,
      logPrefix: NAME,
      reason: "no dynamic workflow jobs on GitHub-hosted runners",
    });
    return;
  }

  log.info(
    `[${NAME}] ${repo.fullName}: ${violations.length} dynamic workflow job(s) on GitHub-hosted runners`,
  );
  await ensureAlertIssue({
    repo: repo.fullName,
    title: ISSUE_TITLE,
    body: buildBody(repo.fullName, violations),
    labels: [LABELS.priority],
    logPrefix: NAME,
  });
}

export async function run(repos: Repo[]): Promise<void> {
  await mapSettledWithConcurrency(repos, REPO_CONCURRENCY, async (repo) => {
    try {
      await scanRepo(repo);
    } catch (err) {
      await reportError(`${NAME}:process-repo`, repo.fullName, err);
    }
  });
}
