import fs from "node:fs";
import path from "node:path";
import { type Repo } from "../config.js";
import { runRepoScanner, type ScannerSpec } from "./scanner-runner.js";

const NAME = "gitignore-scanner";
const ISSUE_TITLE = "chore: add .mcp-claws.json to .gitignore";
const GITIGNORE_ENTRY = ".mcp-claws.json";

function hasGitignoreEntry(content: string): boolean {
  return content.split("\n").some((line) => line.trimEnd() === GITIGNORE_ENTRY);
}

function formatIssueBody(): string {
  return [
    "`.mcp-claws.json` (auto-generated by Claws when invoking Claude) should be in `.gitignore` so it is not accidentally committed.",
    "",
    "Add the following line to `.gitignore`:",
    "",
    "```",
    GITIGNORE_ENTRY,
    "```",
  ].join("\n");
}

function scan(repoDir: string, _repo: Repo): { body: string; summary?: string } | null {
  const gitignorePath = path.join(repoDir, ".gitignore");
  const content = fs.existsSync(gitignorePath)
    ? fs.readFileSync(gitignorePath, "utf-8")
    : "";
  if (hasGitignoreEntry(content)) return null;
  return { body: formatIssueBody(), summary: "Missing .mcp-claws.json gitignore entry" };
}

const SPEC: ScannerSpec = {
  name: NAME,
  issueTitle: ISSUE_TITLE,
  searchQuery: ISSUE_TITLE,
  scan,
};

export function run(repos: Repo[]): Promise<void> {
  return runRepoScanner(SPEC, repos);
}
