#!/usr/bin/env node
// Compiles src/client/*.ts entrypoints with esbuild and writes
// src/resources/<name>.generated.ts modules that export the bundled JS as a
// `<script>…</script>` string. Page builders interpolate those constants the
// same way they interpolate Tailwind/Alpine. The generated files are checked
// in so `npm run build` does not require esbuild at consumer install time.
//
// Authoring contract: write client code as TypeScript in src/client/*.ts with
// strict-mode DOM type-checking. Run `npm run build:client` to regenerate. Do
// not edit src/resources/*.generated.ts by hand — they are overwritten.
import { spawnSync } from "node:child_process";
import { build } from "esbuild";
import { readdirSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const clientDir = resolve(repoRoot, "src/client");
const resourcesDir = resolve(repoRoot, "src/resources");

if (!existsSync(clientDir)) {
  console.log(`No client directory at ${clientDir} — nothing to build.`);
  process.exit(0);
}

// Step 1: type-check with the client tsconfig (DOM lib, strict). esbuild
// does the bundling but does not type-check, so this is the gate.
const tc = spawnSync("npx", ["tsc", "-p", "tsconfig.client.json"], {
  cwd: repoRoot,
  stdio: "inherit",
});
if (tc.status !== 0) {
  process.exit(tc.status ?? 1);
}

// Step 2: bundle each entrypoint (skip *.test.ts and *.d.ts).
const entries = readdirSync(clientDir).filter(
  (f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".d.ts"),
);

if (entries.length === 0) {
  console.log("No client entrypoints to bundle.");
  process.exit(0);
}

mkdirSync(resourcesDir, { recursive: true });

for (const file of entries) {
  const result = await build({
    entryPoints: [resolve(clientDir, file)],
    bundle: true,
    write: false,
    format: "iife",
    target: "es2020",
    minify: true,
    platform: "browser",
    sourcemap: false,
    logLevel: "info",
  });
  if (!result.outputFiles.length) {
    console.error(`esbuild produced no output for ${file}`);
    process.exit(1);
  }
  const js = result.outputFiles[0].text;
  const stem = basename(file, ".ts");
  const constName = stem.toUpperCase().replace(/-/g, "_") + "_SCRIPT";
  // Escape for embedding inside a JS template-literal.
  const escaped = js
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n");
  const outPath = resolve(resourcesDir, `${stem}.generated.ts`);
  const header =
    "// Generated by scripts/build-client.mjs — do not edit by hand.\n" +
    `// Source: src/client/${file}\n` +
    "// Run `npm run build:client` after editing the source.\n";
  // Include the wrapping <script>…</script> so consumers can interpolate the
  // constant directly into HTML, matching the existing ALPINE_SCRIPT /
  // THEME_SCRIPT convention.
  writeFileSync(
    outPath,
    `${header}export const ${constName} = \`<script>${escaped}</script>\`;\n`,
  );
  console.log(`Wrote ${outPath} (${js.length} bytes JS, const ${constName})`);
}
