#!/usr/bin/env node

/**
 * Claws MCP Server — exposes Claws operational state to Claude sessions.
 *
 * Runs as a stdio-based MCP server spawned by Claude CLI via --mcp-config.
 * Provides six core tools: claws_status, claws_task_history, claws_open_prs,
 * claws_config, claws_issue_phases, claws_wait_for_change (and the read-only
 * diagnostics and native-issue attachment tools alongside them, plus the
 * write tools claws_create_issue and claws_comment_on_issue — #3286 — which
 * headless agents get too), plus
 * claws_set_session_title and claws_set_session_status when
 * CLAWS_MCP_SESSION_ID is set (interactive sessions only), the planner tools
 * (claws_save_plan + claws_report_outcome, or claws_step_back_verdict in a
 * step-back pass; see planner-tools.ts) when CLAWS_MCP_PLANNER_RUN_ID is set
 * (one planner invocation only, with CLAWS_MCP_PLANNER_STAGE,
 * CLAWS_MCP_PLANNER_OFFERS and CLAWS_MCP_PLANNER_ALLOW_OUTCOMES — the last
 * omits claws_report_outcome entirely for a plan-only run), claws_save_requirements
 * when CLAWS_MCP_REQUIREMENTS_OUT is set (one requirements-writer invocation
 * only; see requirements-tools.ts), and optionally
 * ha_list_entities / ha_api_request when
 * HOME_ASSISTANT_BASE_URL + HOME_ASSISTANT_TOKEN are configured. The
 * claws-state tools are defined in claws-state-tools.ts; this process supplies
 * their data sources.
 */

import * as diagnosticQueries from "./diagnostic-queries.js";
import fs from "node:fs";
import path from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { createSqliteDriver, type SqlDriver } from "./db-driver.js";
import { z } from "zod";
import { handleListEntities, handleApiRequest } from "./ha-mcp.js";
import { registerClawsStateTools } from "./claws-state-tools.js";
import { registerPlannerTools, parsePlannerOffers, isPlannerToolStage } from "./planner-tools.js";
import { registerRequirementsTools } from "./requirements-tools.js";
import { readInternalMcpToken, readMcpTokenFile, internalMcpTokenPath } from "./internal-mcp-token.js";
import { resolveIssueAttachmentPath } from "./session-uploads-core.js";
// The same rule `db.ts` applies, from the same leaf module: this process reads
// `tasks` with its own driver rather than through `db.ts`'s accessors, and the
// column is TEXT so it can hold a native `clw_…` id (#3215). Any further direct
// query added below has to be wrapped the same way.
import { normalizeItemNumbers } from "./issue-id.js";

const ConfigSnapshotSchema = z.object({
  skippedItems: z.array(z.unknown()).optional(),
  prioritizedItems: z.array(z.unknown()).optional(),
}).passthrough();

const WORK_DIR = process.env["CLAWS_MCP_WORK_DIR"] ?? "";
const PORT = process.env["CLAWS_MCP_PORT"] ?? "3000";
// Fallback only. The live token is read from WORK_DIR on every call: this
// process can outlive several Claws restarts, and INTERNAL_MCP_TOKEN is
// regenerated by each one (#2918).
const FALLBACK_AUTH_TOKEN = process.env["CLAWS_MCP_AUTH_TOKEN"] ?? "";
// An agent pod reads its own token from its Secret volume instead of WORK_DIR.
const AUTH_TOKEN_FILE = process.env["CLAWS_MCP_AUTH_TOKEN_FILE"] ?? "";
const HA_BASE_URL = process.env["HOME_ASSISTANT_BASE_URL"] ?? "";
const HA_TOKEN = process.env["HOME_ASSISTANT_TOKEN"] ?? "";
const SESSION_ID = process.env["CLAWS_MCP_SESSION_ID"] ?? "";
const PLANNER_RUN_ID = process.env["CLAWS_MCP_PLANNER_RUN_ID"] ?? "";
const PLANNER_STAGE = process.env["CLAWS_MCP_PLANNER_STAGE"] ?? "";
const PLANNER_OFFERS = process.env["CLAWS_MCP_PLANNER_OFFERS"] ?? "";
const PLANNER_ALLOW_OUTCOMES = process.env["CLAWS_MCP_PLANNER_ALLOW_OUTCOMES"] !== "false";
const REQUIREMENTS_OUT = process.env["CLAWS_MCP_REQUIREMENTS_OUT"] ?? "";

// One driver for the life of this child process. For SQLite a per-call open was
// cheap; for Postgres a per-call open meant a fresh Pool (and its ~63 s first-
// connect retry) on every tool call against the shared, connection-capped
// instance, so the handle is created once and never closed here.
let cachedDb: Promise<SqlDriver | null> | null = null;

function openDb(): Promise<SqlDriver | null> {
  if (!cachedDb) cachedDb = createDb();
  return cachedDb;
}

async function createDb(): Promise<SqlDriver | null> {
  // An agent pod holds no database credentials and has no claws.db: its
  // DB-backed tools report no database.
  if (AUTH_TOKEN_FILE) return null;
  const url = process.env["CLAWS_DATABASE_URL"] ?? "";
  if (url) {
    // Dynamic so the SQLite path never loads `pg` (or the wasm PGlite import
    // behind it) into this standalone process. db-driver-pg.ts is itself a
    // leaf module — no log/db/config chain — so the Postgres path stays
    // self-contained too.
    const { createPgDriver } = await import("./db-driver-pg.js");
    return createPgDriver({ url, password: process.env["CLAWS_DATABASE_PASSWORD"] ?? "", max: 2 });
  }
  return createSqliteDriver(path.join(WORK_DIR, "claws.db"), { readonly: true });
}

/** A `fetchApi` bound to `baseUrl`, sending this process's bearer token with every call. */
function fetchApiFrom(baseUrl: string) {
  return async function fetchApi(pathAndQuery: string, timeoutMs = 5000, init?: { method: string; body: unknown }): Promise<unknown> {
    const url = `${baseUrl}${pathAndQuery}`;
    const headers: Record<string, string> = {};
    const token = AUTH_TOKEN_FILE
      ? readMcpTokenFile(AUTH_TOKEN_FILE, FALLBACK_AUTH_TOKEN)
      : readInternalMcpToken(WORK_DIR, FALLBACK_AUTH_TOKEN);
    if (token) {
      headers["Authorization"] = `Bearer ${token}`;
    }
    const fetchInit: RequestInit = { headers, signal: AbortSignal.timeout(timeoutMs) };
    if (init) {
      headers["Content-Type"] = "application/json";
      fetchInit.method = init.method;
      fetchInit.body = JSON.stringify(init.body);
    }
    const res = await fetch(url, fetchInit);
    if (!res.ok) {
      const body = (await res.json().catch(() => null)) as { error?: unknown } | null;
      const detail = typeof body?.error === "string" ? `: ${body.error}` : "";
      if (res.status === 401) {
        throw new Error(
          `HTTP 401${detail} — ${baseUrl} rejected this process's credential. ` +
          `The live token is published at ${AUTH_TOKEN_FILE || internalMcpTokenPath(WORK_DIR)}; ` +
          `check the server at that URL is running and that file is readable by this user.`,
        );
      }
      throw new Error(`HTTP ${res.status}${detail}`);
    }
    return res.json();
  };
}

// An agent pod's MCP child reaches the service over the cluster network (CLAWS_MCP_BASE_URL).
const SERVICE_BASE_URL = process.env["CLAWS_MCP_BASE_URL"] ?? `http://localhost:${PORT}`;
const fetchApi = fetchApiFrom(SERVICE_BASE_URL);
// The planner tools post to whichever process holds the planner-run registry:
// the service for an in-process run, or the pod's own loopback listener
// (CLAWS_MCP_PLANNER_BASE_URL, set by claude.ts inside an agent pod) —
// #clw_01M3A42ZTGECAB11S0BZA6NG1A.
const fetchPlannerApi = fetchApiFrom(process.env["CLAWS_MCP_PLANNER_BASE_URL"] || SERVICE_BASE_URL);

// ── MCP Server ──

const server = new McpServer({
  name: "claws-state",
  version: "1.0.0",
});

registerClawsStateTools(server, {
  runningTasks: async () => {
    const db = await openDb();
    if (!db) return null;
    return normalizeItemNumbers(await db.all(
      `SELECT job_name, repo, item_number, started_at FROM tasks WHERE status = 'running' ORDER BY started_at ASC`,
    ));
  },
  taskHistory: async (repo, itemNumber) => {
    const db = await openDb();
    if (!db) return null;
    if (itemNumber !== undefined) {
      return normalizeItemNumbers(await db.all(`
        SELECT t.job_name, t.item_number, t.status, t.error, t.outcome, t.started_at, t.completed_at,
               jr.job_name AS run_job
        FROM tasks t
        LEFT JOIN job_runs jr ON t.run_id = jr.run_id
        WHERE t.repo = ? AND t.item_number = ?
        ORDER BY t.started_at DESC LIMIT 20
      `, [repo, String(itemNumber)]));
    }
    return normalizeItemNumbers(await db.all(`
      SELECT t.job_name, t.item_number, t.status, t.error, t.outcome, t.started_at, t.completed_at,
             jr.job_name AS run_job
      FROM tasks t
      LEFT JOIN job_runs jr ON t.run_id = jr.run_id
      WHERE t.repo = ?
      ORDER BY t.started_at DESC LIMIT 20
    `, [repo]));
  },
  recentJobRuns: async (limit, jobName) => {
    const db = await openDb();
    return db ? diagnosticQueries.getMcpRecentJobRuns(db, limit, jobName) : null;
  },
  recentJobLogs: async (opts) => {
    const db = await openDb();
    return db ? diagnosticQueries.getMcpRecentJobLogs(db, opts) : null;
  },
  workQueue: async ({ statuses, limit }) => {
    const db = await openDb();
    return db ? diagnosticQueries.getMcpWorkQueue(db, limit, statuses) : null;
  },
  repoProcessingState: async (opts) => {
    const db = await openDb();
    return db ? diagnosticQueries.getMcpRepoProcessingState(db, opts) : null;
  },
  openPrs: async (repo) => fetchApi(`/api/open-prs?repo=${encodeURIComponent(repo)}`, 30_000),
  fetchApi,
  issueAttachments: async (issueId) => {
    const db = await openDb();
    if (!db) return null;
    return (await diagnosticQueries.getIssueAttachmentRows(db, issueId)).map(({ stored_path: _path, ...meta }) => meta);
  },
  issueAttachment: async (issueId, attachmentId) => {
    const db = await openDb();
    if (!db) return null;
    const row = (await diagnosticQueries.getIssueAttachmentRows(db, issueId)).find((r) => r.id === attachmentId);
    if (!row) return undefined;
    // The same escape check `issue-attachments.ts` applies: a tampered row
    // must not read a file outside the store.
    const file = resolveIssueAttachmentPath(WORK_DIR, row.stored_path);
    if (!file) return undefined;
    const { stored_path: _path, ...meta } = row;
    return {
      meta,
      read: () => fs.promises.readFile(file),
      // This process has no prompt guard (it would drag in config), so it
      // fails closed: no text preview, metadata only.
      guardText: () => null,
    };
  },
  configSnapshot: async () => {
    const raw = fs.readFileSync(path.join(WORK_DIR, "config.json"), "utf-8");
    const config = ConfigSnapshotSchema.parse(JSON.parse(raw));
    return { skippedItems: config.skippedItems ?? [], prioritizedItems: config.prioritizedItems ?? [] };
  },
  sessionId: SESSION_ID,
});

// Tools: claws_save_plan / claws_report_outcome / claws_step_back_verdict — only
// in a config written for one planner run, and only ever for that run.
if (PLANNER_RUN_ID && isPlannerToolStage(PLANNER_STAGE)) {
  registerPlannerTools(server, {
    runId: PLANNER_RUN_ID,
    stage: PLANNER_STAGE,
    offers: parsePlannerOffers(PLANNER_OFFERS),
    outcomes: PLANNER_ALLOW_OUTCOMES,
    fetchApi: fetchPlannerApi,
  });
}

// Tool: claws_save_requirements — only in a config written for one
// requirements-writer run, writing to that run's out file.
if (REQUIREMENTS_OUT) registerRequirementsTools(server, { outFile: REQUIREMENTS_OUT });

// Tool: ha_list_entities + ha_api_request — only registered when HA is configured
if (HA_BASE_URL && HA_TOKEN) {
  server.tool(
    "ha_list_entities",
    "List Home Assistant entity IDs with current state and friendly name. Use this to discover entities when writing automations/scripts. Optionally filter by domain (e.g. 'light', 'sensor') or a search substring. Returns a projected, capped list — for full attributes of one entity use ha_api_request with /api/states/{entity_id}.",
    {
      domain: z.string().optional().describe("Entity domain prefix, e.g. 'light'"),
      search: z.string().optional().describe("Case-insensitive substring matched against entity_id and friendly name"),
    },
    async ({ domain, search }) => handleListEntities(HA_BASE_URL, HA_TOKEN, { domain, search }),
  );
  server.tool(
    "ha_api_request",
    "Make an arbitrary request to the Home Assistant REST API and return the response. Gives full access to HA. path must be a relative path beginning with /api/. Common GET paths: /api/states/{entity_id}, /api/services, /api/config, /api/error_log, /api/history/period/{ISO8601}?filter_entity_id=..., /api/logbook/{ISO8601}. POST examples: /api/template with body {\"template\":\"{{ states('sun.sun') }}\"}; /api/services/{domain}/{service} with body of service data to invoke a service. Responses are truncated at 50k chars.",
    {
      method: z.enum(["GET", "POST"]).optional().describe("HTTP method, default GET"),
      path: z.string().describe("Relative HA API path beginning with /api/"),
      body: z.record(z.string(), z.unknown()).optional().describe("JSON body for POST requests"),
    },
    async ({ method, path: apiPath, body }) => handleApiRequest(HA_BASE_URL, HA_TOKEN, { method, path: apiPath, body }),
  );
}

// ── Start ──

const transport = new StdioServerTransport();
await server.connect(transport);
