/** Env keys that must never leak into a child/interactive session in strict mode. */
export const SENSITIVE_ENV_KEYS = [
  "CLAWS_HOME_ASSISTANT_TOKEN", "HOME_ASSISTANT_TOKEN",
  "NAMEY_DB_URL", "CLAWS_NAMEY_DB_URL",
  "OPENAI_API_KEY",
  "CLAWS_OPENROUTER_API_KEY", "OPENROUTER_API_KEY",
  "CLAWS_AUTH_TOKEN",
  "CLAWS_OIDC_CLIENT_SECRET",
  "CLAWS_SLACK_BOT_TOKEN", "CLAWS_SLACK_WEBHOOK", "CLAWS_SLACK_WEBHOOK_URL",
  "BRENDAN_SERVER_GMAIL_APP_PASSWORD",
] as const;
